### ISSUE TITLE
No translate some words

### ISSUE THREAD

**Issue by AircraftRu** [stdonato/glpi-dashboard#1]
Section settings are not translated words into Russian (ru_RU):
![glpi - dashboard - home - google chrome 2016-10-26 11 43 01](https://cloud.githubusercontent.com/assets/17082164/19719864/7505165e-9b74-11e6-9500-c4e17624739a.png)

**Comment by stdonato** [comment]
how do write  popup in russian?

**Comment by AircraftRu** [comment]
"popup" = "всплывающие уведомления"

"Due date"  = "срок выполнения"

"Due date" is not translate only in version 9.1 GLPI . 
In 0.90.5 traslated.
