### ISSUE TITLE
assets link doesnt work

### ISSUE THREAD

**Issue by roshanroche** [stdonato/glpi-dashboard#11]
Dear Steven,

when i click on monitors or printers on asset page in dashboard doesnt show anything after i upgrade to new version. with the old version it was fine. 
computer link shows graph as well as lists the items.

**Comment by stdonato** [comment]
Fixed.

**Comment by roshanroche** [comment]
Thank you.
can i get the fix?

**Comment by stdonato** [comment]
I will upload to git later.

**Comment by roshanroche** [comment]
Thank you so much
