### ISSUE TITLE
no solved data on metrics page

### ISSUE THREAD

**Issue by roshanroche** [stdonato/glpi-dashboard#12]
Dear Steven,
on the metrics page there is new assigned pending closed items for tickets , but doesnt show the ones marked as SOLVED.

**Comment by stdonato** [comment]
What time period is selected in config page?

**Comment by roshanroche** [comment]
Total or anything u select. it doesnt show solved tickets. it only shows closed tickets

**Comment by stdonato** [comment]
Your GLPI is configured to close tickets after a time period or immediately?  Depending on your GLPI settings, none tickets will be tagged as solved.

**Comment by roshanroche** [comment]
users can change the status to solved , and in my tickets menu it shows the statistics of solved tickets. even in ur modification plugin it shows me solved statistics. but in dashboard plugin menu metrics page SOLVED tickets missing.

**Comment by stdonato** [comment]
Ok. I will test and fix, if necessary.

**Comment by roshanroche** [comment]
Thank you.

**Comment by stdonato** [comment]
Assets fix uploaded.

**Comment by roshanroche** [comment]
Thank you
