### ISSUE TITLE
Total Ticket Task Time missing

### ISSUE THREAD

**Issue by nushahid** [stdonato/glpi-dashboard#13]
hi,
First of all i really appreciate last version of dashboard. it's really looking so nice,
Secondly i notice that there should be a Total ticket task time in reports. One report is continuously missing about total task time related to tickets.
e.g report-> summary-> by requester -> ticket section
it didn't have total task activity time. if you put it there, that would be a nice option to find every thing in one page summary.
other way, report ->task->tickets there should be a requester. to count total task time and list of tasks related to specific requester. 
rest everything is perfect. I noticed that you continuously missing about tasks statistics. it exists in GLPI ticket's statistics. but it should be a good to see in summary page. 

Thanks

**Comment by stdonato** [comment]
Hi, i made some of your sugestions and added a new report from tasks by
requester (ticket requester).
Try this version:
https://drive.google.com/file/d/0B2-Kr9P1ubw9M0Z3bUVMVkVKWjg/view?usp=sharing


2017-03-13 17:30 GMT-04:00 nushahid <notifications@github.com>:

**Comment by nushahid** [comment]
awsome! works perfectly
i noticed export to pdf didn't has total tasks time. by the way it's not important.
thanks for quick response... great work
