### ISSUE TITLE
Tickets and tasks in one report

### ISSUE THREAD

**Issue by pszafer** [stdonato/glpi-dashboard#16]
Hello,

Like your plugin very much.
I know that there are "Tickets by Technician" and "Tasks by Technician" reports.
Is there report which showing both in one table, like nested:

- ticket1
  - task1 of ticket1
  - task2 of ticket1
- ticket2
   - task1 of ticket2

Do you have time to write such report? if not I think it is simple enough to make it by myself if you are interested in adding it to plugin

**Comment by stdonato** [comment]
Hello,

Thank's for your feedback.
I will try make this report, but if you want make your version, will be a
great help.

Regards,

Stevenes Donato


2017-03-22 15:15 GMT-04:00 Pawel <notifications@github.com>:

**Comment by stdonato** [comment]
Hi, i was able to change the tasks by tickets report to show the task grouped by tickets, like you suggested. I will update the github and you can test.

**Comment by pszafer** [comment]
great,
is it already updated?
