### ISSUE TITLE
 Map Reporting does not work

### ISSUE THREAD

**Issue by cr1stt0f3r** [stdonato/glpi-dashboard#17]
The report by map in this last version, 0.8.2 does not present the map, showing error .. continuing the problem of when clicked on top of the entity, does not redirect to the calls of the selected entity.

The version I use most stable in this feature is 0.7.0 ..

Could you consider this question?
![capturar](https://cloud.githubusercontent.com/assets/26659061/24309584/28a31f66-10ab-11e7-8de3-adbb55591e80.PNG)

**Comment by stdonato** [comment]
Hi, have you inserted the google maps API key? About the links, the search in GLPI has changed. i will fix them for new version.

**Comment by cr1stt0f3r** [comment]
yes, the key are installed..
Worst of all is that I performed an uninstallation and re-put a 0.7.9 version, cleared the browser history and a map report not the same as before.
![capturar](https://cloud.githubusercontent.com/assets/26659061/24310540/16d398c0-10af-11e7-84cd-25b08a267a1e.PNG)

**Comment by stdonato** [comment]
O mapa funcionava e então parou? Recomendo usar a versão 0.8.2, com a chave do google maps. Verifique se o acesso à internet do seu servidor está fucionando. Se for servidor linux pode testar executando o wget com o url do maps:  wget https://maps.googleapis.com/maps/api/js?sensor=false

**Comment by cr1stt0f3r** [comment]
Desculpe, deixe-me detalhar...

O mapa só funciona de acordo (exceto direcionar para os chamados da entidade quando clicado) na versão 0.7.0.

O teste feito com a ultima versão, 0.8.2, ele acontece como descrito no print 1.
A chave do Google Maps foi inserida.

Após desabilitar o plugin e deletar a pasta do plugin da estrutura do GLPI, eu re-instalei a versão 0.7.0. Fiz limpeza do navegador completo, e os menus permaneceram como na print2, ficando da mesma forma que a versão 0.8.2.

Em minha opinião, a versão 0.7.0 é a mais estável no quesito de mapas, é muito bom e atende de acordo! Tendo apenas a salvaguarda de não chamar corretamente a lista de chamados da entidade clicada.

Item importante, pois, acredito que devo ser um bom exemplo de teste, pois tenho mais de 50 entidades cadastradas fazendo uso de mapas.

Por favor, não me entenda mal, só estou tentando dar um feedback para a melhoria como um todo..

**Comment by stdonato** [comment]
Sem problema, pode questionar à vontade. Uma coisa que esqueci de perguntar é se seu servidor é local ou hospedado. Até a versão 0.8.1 o mapa não funcionava na maioria das hospedagens, por isso inlcui a chave de API do maps, então passou a funcionar. Diversos usuários reportaram que funciona corretamente. Quanto aos links para a lista de chamados já corrigi, pois foram alterados no próprio GLPI.

**Comment by cr1stt0f3r** [comment]
Server local.
Nos testes da ultima versão, esta questão do link para a lista de chamados também nao funciona..
