### ISSUE TITLE
SQL error in a fresh install

### ISSUE THREAD

**Issue by wanderleihuttel** [stdonato/glpi-dashboard#18]
Hello Stevenes

In a fresh install when you don't have any tickets I'm receiving a SQL error:
SQL: SELECT COUNT(glpi_tickets.id) as total
      FROM glpi_tickets
      LEFT JOIN glpi_entities ON glpi_tickets.entities_id = glpi_entities.id
      WHERE glpi_tickets.is_deleted = \'0\'
      AND DATE_FORMAT( glpi_tickets.date, \'%Y\' ) IN ()
      AND glpi_tickets.entities_id IN (0,1)
  Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')
      AND glpi_tickets.entities_id IN (0,1)' at line 5
  Backtrace :
  plugins/dashboard/front/main.php:273

Best Regards
Wanderlei

**Comment by stdonato** [comment]
Fixed.
