### ISSUE TITLE
graficos

### ISSUE THREAD

**Issue by thifranco** [stdonato/glpi-dashboard#19]
estou com problemas para mostrar os graficos assim que entro no painel, ocorreu apos eu restaurar a pasta files depois de migrar o servidor. Antes de mover a pasta files antiga funcionava normalmente. Alguma idea do que posso verificar ?
![temp](https://user-images.githubusercontent.com/20299682/27293680-7c5978cc-54ed-11e7-9470-93322c048ffe.PNG)

**Comment by stdonato** [comment]
Verifique as permissões.
