### ISSUE TITLE
Dashboard not working - PHP Fatal error

### ISSUE THREAD

**Issue by Teraxi** [stdonato/glpi-dashboard#20]
Hello,

With a fresh installation of the Dashboard v. 0.8.3 and GLPI 0.9.4 the Dashboard does not function properly. The front page of the Dashboard only loads up to half of the top bar. If I look at the HTML sourcecode the page does not load anything anymore after line 165.

Following error is visible in the Apache error log:
[Mon Jul 10 14:34:46.689380 2017] [:error] [pid 7955] [client] PHP Fatal error:  Uncaught exception 'Zend\\I18n\\Exception\\OutOfBoundsException' with message 'Provided index 1 does not exist in plural array' in /srv/www/doc-center/vendor/zendframework/zend-i18n/src/Translator/Translator.php:413\nStack trace:\n#0 /srv/www/doc-center/inc/autoload.function.php(171): Zend\\I18n\\Translator\\Translator->translatePlural('Technician', 'Technicians', 2, 'dashboard')\n#1 /srv/www/doc-center/plugins/dashboard/front/index1.php(313): _n('Technician', 'Technicians', 2, 'dashboard')\n#2 {main}\n  thrown in /srv/www/doc-center/vendor/zendframework/zend-i18n/src/Translator/Translator.php on line 413

To work around the problem it seems that if I change my language on my user profile to anything else except English or English (US) the page loads properly.

**Comment by stdonato** [comment]
Hi,
Thank you for your feedback. Seens to be a error in translation files.
I will check and fix for next version.

Regards,

Stevenes Donato


2017-07-10 7:39 GMT-04:00 Teraxi <notifications@github.com>:

**Comment by stdonato** [comment]
Fixed
