### ISSUE TITLE
Error on Install Plugin

### ISSUE THREAD

**Issue by cr1stt0f3r** [stdonato/glpi-dashboard#22]
I am having problems installing the plugin, presenting this error in the installation 0.8.5:

Error update table glpi_plugin_dashboard_map primary key Duplicate entry 'Curitibanos' for key 'location'

I imagine it is for identifying duplicate unnamed entities, where you have sub-levels of entities ..

PMSC> Curitibanos
Penitentiary> Curitibanos

How did you proceed?
Thank you!

**Comment by stdonato** [comment]
.

**Comment by cr1stt0f3r** [comment]
I have tested the latest plugin and the latest version of GLPI 9.4.2 and is still experiencing a double location error ...
Do you recommend any alternatives?
