### ISSUE TITLE
Metrics - GLPI 9.2

### ISSUE THREAD

**Issue by dordetto** [stdonato/glpi-dashboard#24]
Hello, after update to GLPI 9.2 and reinstall Dashboard, the link METRICS in menu bar does not working.

When I click, return error: HTTP ERROR 500

Thanks a lot.

**Comment by stdonato** [comment]
Hi,
I'm working in a compatible version. I will release as soon as possible.

Regards,
Stevenes Donato

Em 2 de out de 2017 2:20 PM, "dordetto" <notifications@github.com> escreveu:

**Comment by JulienG78** [comment]
Hi, same problem here :( I'm also investigating on this case.

**Comment by stdonato** [comment]
Hi, try version 0.8.8.

**Comment by stdonato** [comment]
.
