### ISSUE TITLE
[0.8.8] undefined variables php notice

### ISSUE THREAD

**Issue by ladenree76000** [stdonato/glpi-dashboard#27]
see also http://forum.glpi-project.org/viewtopic.php?pid=341268#p341268

PHP Notice: Use of undefined constant computers - assumed 'computers' in /var/www/html/glpi92/plugins/dashboard/front/assets/assets.php at line 256
PHP Notice: Use of undefined constant monitors - assumed 'monitors' in /var/www/html/glpi92/plugins/dashboard/front/assets/assets.php at line 259
PHP Notice: Use of undefined constant printers - assumed 'printers' in /var/www/html/glpi92/plugins/dashboard/front/assets/assets.php at line 262
PHP Notice: Use of undefined constant networkequipments - assumed 'networkequipments' in /var/www/html/glpi92/plugins/dashboard/front/assets/assets.php at line 265
PHP Notice: Use of undefined constant phones - assumed 'phones' in /var/www/html/glpi92/plugins/dashboard/front/assets/assets.php at line 268
PHP Notice: Use of undefined constant peripherals - assumed 'peripherals' in /var/www/html/glpi92/plugins/dashboard/front/assets/assets.php at line 271
PHP Notice: Use of undefined constant softwares - assumed 'softwares' in /var/www/html/glpi92/plugins/dashboard/front/assets/assets.php at line 274
PHP Notice: Use of undefined constant cartridgeitems - assumed 'cartridgeitems' in /var/www/html/glpi92/plugins/dashboard/front/assets/assets.php at line 277
PHP Notice: Use of undefined constant consumableitems - assumed 'consumableitems' in /var/www/html/glpi92/plugins/dashboard/front/assets/assets.php at line 280

**Comment by stdonato** [comment]
Hi. Already fixed. Thank you for the feedback.

**Comment by stdonato** [comment]
Hi. Already fixed. Thank you for the feedback.
