### ISSUE TITLE
Files not found

### ISSUE THREAD

**Issue by hgpit** [stdonato/glpi-dashboard#3]
Just upgraded our GLPI to v9.1.1 (on CentOS v6.8) and thought we'd give Dashboard 0.7.8 a whirl.

Love the look and feel but there seems to be quite a few bugs which break functionality:

- Apache error: "[Mon Nov 28 09:18:02 2016] [error] [client 10.11.23.202] File does not exist: /usr/share/glpi/plugins/dashboard/front/less/datepicker.less, referer: http://helpdesk.hayley-group.local/plugins/dashboard/front/graficos/graf_tech.php?con=1"

- Apache error: "[Mon Nov 28 09:43:27 2016] [error] [client 10.11.23.202] File does not exist: /usr/share/glpi/plugins/dashboard/front/css/bootstrap.css.map"

- Apache error: "[Mon Nov 28 09:48:54 2016] [error] [client 10.11.23.202] File does not exist: /usr/share/glpi/plugins/dashboard/front/css/style-, referer: http://helpdesk.hayley-group.local/plugins/dashboard/front/graficos/graf_tech.php?date1=2016-01-01&date2=2016-11-28&con=1"

- Apache error: "[Mon Nov 28 09:48:54 2016] [error] [client 10.11.23.202] Directory index forbidden by Options directive: /usr/share/glpi/plugins/dashboard/front/js/themes/, referer: http://helpdesk.hayley-group.local/plugins/dashboard/front/graficos/graf_tech.php?date1=2016-01-01&date2=2016-11-28&con=1"

- Top Menu Error: In Firefox we have a topmenu, which lists a horizontal menu (Dashboard My Dashboard Tickets Reports etc). This doesn't appear in Google Chrome. As my company is a Google house, we would really need Dashboard to play nice with Google Chrome in order to be able to use.

- When using Firefox, we can click on the Assets area, but we receive loads of "red" errors:
"
PHP Notice: Use of undefined constant computers - assumed 'computers' in /usr/share/glpi/plugins/dashboard/front/assets/assets.php at line 237
PHP Notice: Use of undefined constant monitors - assumed 'monitors' in /usr/share/glpi/plugins/dashboard/front/assets/assets.php at line 240
PHP Notice: Use of undefined constant printers - assumed 'printers' in /usr/share/glpi/plugins/dashboard/front/assets/assets.php at line 243
PHP Notice: Use of undefined constant networkequipments - assumed 'networkequipments' in /usr/share/glpi/plugins/dashboard/front/assets/assets.php at line 246
PHP Notice: Use of undefined constant phones - assumed 'phones' in /usr/share/glpi/plugins/dashboard/front/assets/assets.php at line 249
PHP Notice: Use of undefined constant peripherals - assumed 'peripherals' in /usr/share/glpi/plugins/dashboard/front/assets/assets.php at line 252
PHP Notice: Use of undefined constant softwares - assumed 'softwares' in /usr/share/glpi/plugins/dashboard/front/assets/assets.php at line 255
PHP Notice: Use of undefined constant cartridges - assumed 'cartridges' in /usr/share/glpi/plugins/dashboard/front/assets/assets.php at line 258
PHP Notice: Use of undefined constant consumables - assumed 'consumables' in /usr/share/glpi/plugins/dashboard/front/assets/assets.php at line 260
"

- Apache error: "[Mon Nov 28 09:54:46 2016] [error] [client 10.11.23.202] File does not exist: /usr/share/glpi/plugins/dashboard/front/js/extensions/ColVis, referer: http://helpdesk.hayley-group.local/plugins/dashboard/front/tickets/chamados.php"

The more I look around Dashboard, the more awesome this could be.

If you could address the above issues I would be very grateful :)

Thanks in advance.

Elliot

**Comment by stdonato** [comment]
Hi, i will verify and fix errors. 
Thanks for your feedback.

**Comment by edgardmessias** [comment]
Partially fixed in #6
