### ISSUE TITLE
dashboard Report Cost section is not working after update

### ISSUE THREAD

**Issue by nushahid** [stdonato/glpi-dashboard#38]
Hi,
I install a new glpi version 0.9.3.1 for testing in our server 
I tried dashboard plugin 0.9.3 and 0.9.4, but report cost section is not working with my entity.
could you check it please. 

Thanks

**Comment by stdonato** [comment]
Hi,
I will check this.
Thanks for your feedback.



Em qui, 4 de out de 2018 às 04:03, nushahid <notifications@github.com>
escreveu:

**Comment by nushahid** [comment]
It was my mistake. everything is working fine. closing issue. 
Thanks
