### ISSUE TITLE
Erro Custo por Entidade

### ISSUE THREAD

**Issue by francescouk** [stdonato/glpi-dashboard#51]
Toda vez que tento gerar um relatorio de custo por entidade, ele aparece uma mensagem para selecionar a entidade, porem a entidade ja esta selecionada. Lembrando que a entidade utilizada e a root.
![Erro_Custo](https://user-images.githubusercontent.com/1994892/70067625-4ea2ea00-15cd-11ea-84fa-1efa1eacc7fb.png)

**Comment by stdonato** [comment]
Olá. Quais versões do GLPI e Dashboard? 
Como estão configuradas as entidades no config do Dashboard?

**Comment by francescouk** [comment]
Segue:
![Versao_GLPI](https://user-images.githubusercontent.com/1994892/70139593-8cf1e500-1671-11ea-88d7-bd16b5dea7ef.png)
![Versao_Dashboard](https://user-images.githubusercontent.com/1994892/70139602-911e0280-1671-11ea-946b-3075fe52a2d3.png)
![Config_Dashboard](https://user-images.githubusercontent.com/1994892/70139611-94b18980-1671-11ea-8310-e8ca8c530250.png)

**Comment by francescouk** [comment]
Versao do GLPI 9.4.4
Versao do Dashboard 0.98
Quando clico em consultar, ele não assume a entidade raiz e continua pedindo para selecionar uma entidade.

**Comment by stdonato** [comment]
Olá. Seria possível vc fazer o seguinte teste:
No arquivo "/dashboard/front/reports/rel_custo_ent.php"
Na linha 220 substiuir
if($id_ent == "") {
por
if($id_ent == '' || $id_ent == -1) {

**Comment by francescouk** [comment]
O erro nao aparece mais. Porem nao tras nenhum resultado. Segue abaixo caso a consulta for por realizada por requerente utilizando a mesma data:

![Custo_req](https://user-images.githubusercontent.com/1994892/70142107-43a49400-1677-11ea-92c8-1bed26fb65aa.png)

**Comment by francescouk** [comment]
![Custo_ent](https://user-images.githubusercontent.com/1994892/70142286-a4cc6780-1677-11ea-8c88-071f91b550c5.png)

**Comment by francescouk** [comment]
Outra coisa que eu notei, na linha 220 estava o seguinte codigo:
`if($id_ent == 0) {`

**Comment by stdonato** [comment]
Baixe o novo arquivo /front/reports/rel_custo_ent.php  aqui do github e teste, por favor.

**Comment by francescouk** [comment]
Realizei a troca do novo arquivo. Reiniciado o httpd porem a tela nao aparece a entidade nem o botão de consultar:

![Custo_ent2](https://user-images.githubusercontent.com/1994892/70145515-0512d780-167f-11ea-8488-f5d362dde661.png)

**Comment by stdonato** [comment]
Aqui no meu cenário funcionou, exibindo o chamado normalmente. Vou fazer mais testes. Grato pela colaboração.

**Comment by francescouk** [comment]
deu um inspect na pagina e esta aparecendo 2 errros. Nao sei se estao relacionados:
`Failed to load resource: the server responded with a js/themes/default.js:1 status of 404 (Not Found)`

**Comment by francescouk** [comment]
![Erro_js](https://user-images.githubusercontent.com/1994892/70146477-ffb68c80-1680-11ea-862c-5e73dd8c4129.png)

**Comment by francescouk** [comment]
Percebi algumas diferencas no sql. Veja se ajuda:

`// Chamados
	$sql_cham =
	"SELECT glpi_tickets.id AS id, glpi_tickets.name AS name, glpi_tickets.date AS date, glpi_tickets.closedate as closedate,
	glpi_tickets.type, glpi_tickets.status, FROM_UNIXTIME( UNIX_TIMESTAMP( `glpi_tickets`.`closedate` ) , '%Y-%m' ) AS date_unix, AVG( glpi_tickets.solve_delay_stat ) AS time,
	glpi_tickets.solve_delay_stat AS time_sec
	FROM `glpi_tickets_users`, glpi_tickets, glpi_ticketcosts
	WHERE glpi_tickets.id = glpi_tickets_users.`tickets_id`
	AND glpi_tickets_users.type = 2
	AND glpi_ticketcosts.entities_id = ". $id_ent ."
	AND glpi_tickets.is_deleted = 0
	AND glpi_tickets.id = glpi_ticketcosts.`tickets_id`
	AND glpi_tickets.date ".$datas2."
	AND glpi_tickets.status IN ".$status."
	AND glpi_tickets.entities_id IN (".$ents.")
	GROUP BY id
	ORDER BY id DESC ";
	
	$result_cham = $DB->query($sql_cham);`

contra este aqui:

`// Chamados
	$sql_cham =
	"SELECT glpi_tickets.id AS id, glpi_tickets.name AS name, glpi_tickets.date AS date, glpi_tickets.closedate as closedate,
	glpi_tickets.type, glpi_tickets.status, FROM_UNIXTIME( UNIX_TIMESTAMP( `glpi_tickets`.`closedate` ) , '%Y-%m' ) AS date_unix, AVG( glpi_tickets.solve_delay_stat ) AS time,
	glpi_tickets.solve_delay_stat AS time_sec
	FROM `glpi_tickets_users` , glpi_tickets, glpi_ticketcosts
	WHERE glpi_tickets.id = glpi_tickets_users.`tickets_id`
	AND glpi_tickets_users.type = 1
	AND glpi_tickets_users.users_id = ". $id_tec ."
	AND glpi_tickets.is_deleted = 0
	AND glpi_tickets.id = glpi_ticketcosts.`tickets_id`
	AND glpi_tickets.date ".$datas2."
	AND glpi_tickets.status IN ".$status."
	".$entidade."
	GROUP BY id
	ORDER BY id DESC ";
	$result_cham = $DB->query($sql_cham);`

**Comment by francescouk** [comment]
`user type = 1 `e no outro `user type =2`
`AND glpi_tickets.entities_id IN (".$ents.")` e no outro `".$entidade."`

**Comment by francescouk** [comment]
Acredito que encontrei o problema:
mudei o user type de 2 para 1 e ele retornou todos os custos
`AND glpi_tickets_users.type = "1"`

![Custo_ent_suc](https://user-images.githubusercontent.com/1994892/70155790-aacf4200-1691-11ea-84e0-e11d814dd80e.png)

**Comment by stdonato** [comment]
Devo ter cometido algum erro na hora de atualizar o arquivo. Só peço que você fazça mais um teste: onde está type = 1 use type = 2 e veja se gera o relatório.
Mais uma vez obrigado pela colaboração.
