### ISSUE TITLE
Número de Problemas não é Exibido

### ISSUE THREAD

**Issue by pelachim** [stdonato/glpi-dashboard#53]
Quando eu configuro um período: Mês Atual, o número de problemas não é exibido em Métricas -- Geral.

Preciso de uma ajuda.

Alguém?

**Comment by stdonato** [comment]
Funcionando corretamente em três servidores. 
Quais as versões do seu GLPI e Dashboard?
![Firefox_Screenshot_2020-01-30T12-16-17 582Z](https://user-images.githubusercontent.com/7674445/73449193-ff610780-4338-11ea-808e-106a623a4bab.png)

**Comment by pelachim** [comment]
Quando eu exibi o valor total também exibe os problemas, quando eu coloco mes atual, não exibe

Painel | dashboard | 0.9.8
GLPI 9.4.5 Copyright (C) 2015-2019

Metrica Mês atual
![image](https://user-images.githubusercontent.com/48538289/73572207-fbbfa480-444e-11ea-8dff-97ea6d665344.png)

Metrica Total
![image](https://user-images.githubusercontent.com/48538289/73572317-40e3d680-444f-11ea-95c7-0e2d22a746e8.png)

**Comment by stdonato** [comment]
Realmente. Vacilei. Aqui também não exibe. Vou verificar.
Obrigado

**Comment by pelachim** [comment]
Obrigado também, pela rápida resposta.

**Comment by stdonato** [comment]
Olá, faça um teste simples:
No arquivo glpi/plugins/dashboard/front/metrics/metrics.inc.php edite a linha 395.
Onde está  ".$period."   substitua por  ".$periodp."

**Comment by pelachim** [comment]
Show de bola 
Resolvido.

Como faria para ter relatórios dos problemas igual eu tenho para os chamados?
