### ISSUE TITLE
AJUSTE DE DASHBOARD (ATRIBUIDO,PENDENTE,SOLUCIONADO,TOTAL DE ABERTOS)

### ISSUE THREAD

**Issue by cavaquinhow** [stdonato/glpi-dashboard#54]
Quando colocamos o período como MÊS ATUAL, os chamados do mês anterior (ATRIBUÍDOS, PENDENTES e SOLUCIONADOS) não aparecem, bem como os CHAMADOS ABERTOS segundo print abaixo:

![image](https://user-images.githubusercontent.com/60626875/73688873-bf3cb480-46ab-11ea-8064-5b9555121bd8.png)

Segue print do mês anterior.

![image](https://user-images.githubusercontent.com/60626875/73689057-2195b500-46ac-11ea-944f-5157d666e8aa.png)

**Comment by stdonato** [comment]
Olá. 
Mês atual só mostrará chamados do mês corrente, a partir do 1º dia, por exemplo, de 1 a 4 de fevereiro.
ùltimos 30 dias mostrará os chamados da data atual até 30 dias atrás, por exemplo, de 04 de fev a 04 de jan.
