### ISSUE TITLE
[0.9.8] Unable to download CSV of a statistic

### ISSUE THREAD

**Issue by tuxxic** [stdonato/glpi-dashboard#55]
Hello,

I am using the dashboard version 0.9.8 on a GLPI 9.4.5, and when I click on "Download CSV" on a Ticket solution time graph, nothing happens :

![image](https://user-images.githubusercontent.com/4680438/73922650-d0630c80-48c9-11ea-8d1c-98cbedb6e5c7.png)

Can you please tell me what to do?

Thanks in advance,

**Comment by stdonato** [comment]
I will update highcharts in next version
