### ISSUE TITLE
Painel Geral de chamados

### ISSUE THREAD

**Issue by Jonasdart** [stdonato/glpi-dashboard#61]
Olá, amigo!

Estou fazendo testes na versão 9.4.4 do GLPI e identifiquei que a funcionalidade do painel geral não está como era antes. Creio que seja um bug.

Segue imagem para visualização:
https://prnt.sc/rvkjin

**Comment by stdonato** [comment]
Qual versão do plugin?

Em qua, 8 de abr de 2020 13:22, Jonas Duarte <notifications@github.com>
escreveu:

**Comment by duzzsys** [comment]
Em qualquer uma das versões estava dando este erro. Porém, ao rodar a query manualmente, percebi que no meu banco não possui a coluna 'time_to_resolve' na tabela 'glpi_tickets'.

Criei a coluna, a fim de testes, e agora está gerando o painel, porém com um erro de PHP.
Como mostra a imagem:
https://prnt.sc/rvlvr5

**Comment by duzzsys** [comment]
Vale ressaltar, também, que é um banco legado. Utilizado desde a versão 9.1.6 do GLPI. Para migramos para o 9.4.4 falta apenas a compatibilidade com este plugin essencial hoje para a aplicação.

**Comment by duzzsys** [comment]
Prezado, creio que resolvi o problema, levando em consideração que a coluna time_to_resolve migrou-se para a due_date. Alterei as linhas:

327 e 328 do main.php
364, 265, 275 e 291 do tickets/chamados.php

Se me confirmar que isto não impacta negativamente no plugin, formalizo a solução e aplicamos a atualização. Desde já, agradeço e o parabenizo pelo seu trabalho.

**Comment by stdonato** [comment]
Se o erro foi corrigido, tudo bem fazer a modificação, mas lembre que numa atualização pode ser necessário refazer tudo. Já testou a última release, 0.9.8?

**Comment by duzzsys** [comment]
Já teste sim. Continua ocorrendo. Será se é um problema somente com bancos antigos? Pois não há muita incidência desse problema
