### ISSUE TITLE
Mapa e Gráficos não aparecem GLPI 9.4.5

### ISSUE THREAD

**Issue by Phorta** [stdonato/glpi-dashboard#62]
Após atualizar para a versão 9.4.5 o plugin Dashboard não gera o Mapa com os chamados e nenhum relatório no menu Gráficos...
Estou utilizando
- Debian 7,
- MariaDB 10.3.8,
- PHP 7.3.16
- Plugin Dashboard 0.9.8
- GLPI 9.4.5

Ao tentar gerar qualquer relatório no menu "Gráfico" aparece a opção de preencher o período, porem em baixo fica tela branca...
Ao tentar gerar o Chamado > Mapa > Por entidade o sintoma é o mesmo acima, aparece a opção de período e tipos de chamados mas não gera o mapa.. fica em branco...

**Comment by stdonato** [comment]
Olá. Os gráficos da tela inicial do plugin aparecem? 
Se quiser testar  a versã o mais recente, com algumas correções, baixe o arquivos ZIP direto do repositório (em Clone or download), descompacte e renomeie a pasta para "dashboard."

**Comment by Phorta** [comment]
Ola,
Resolvido essa questão...
Dei permissão na pasta siles/_cache e o mapa e os gráficos estão funcionando perfeitamente.
