### ISSUE TITLE
Erros ao abrir métricas

### ISSUE THREAD

**Issue by allcomnet** [stdonato/glpi-dashboard#63]
Estamos com erro em nosso Dashboard ver. 0.9.8, na tela de métricas recebemos erro 500, quando ativamos o modo DEBUG do GLPI ver. 9.4.5 obtivemos os seguintes erros:

Na coluna de chamados abertos por técnico:

Fatal error: Uncaught Error: Call to a member function fetch_assoc() on bool in /var/www/html/glpi/inc/dbmysql.class.php:330 Stack trace: #0 /var/www/html/glpi/plugins/dashboard/front/main.php(704): DBmysql->fetch_assoc() #1 {main} thrown in /var/www/html/glpi/inc/dbmysql.class.php on line 330

Em Métricas -> Geral

PHP Notice: Trying to get property 'num_rows' of non-object in /var/www/html/glpi/inc/dbmysql.class.php at line 296

Fatal error: Uncaught Error: Call to a member function fetch_assoc() on bool in /var/www/html/glpi/inc/dbmysql.class.php:330 Stack trace: #0 /var/www/html/glpi/plugins/dashboard/front/metrics/metrics.inc.php(319): DBmysql->fetch_assoc() #1 /var/www/html/glpi/plugins/dashboard/front/metrics/index.php(21): include('/var/www/html/g...') #2 {main} thrown in /var/www/html/glpi/inc/dbmysql.class.php on line 330

Erro na tela de Configurar:

PHP Warning: Invalid argument supplied for foreach() in /var/www/html/glpi/plugins/dashboard/front/config.php at line 107
PHP Warning: Invalid argument supplied for foreach() in /var/www/html/glpi/plugins/dashboard/front/config.php at line 316

Log do APACHE:

[Fri Jun 05 11:36:22.699293 2020] [php7:error] [pid 5848] [client 192.168.0.135:56213] PHP Fatal error:  Uncaught Error: Call to a member function fetch_assoc() on bool in /var/www/html/glpi/inc/dbmysql.class.php:330\nStack trace:\n#0 /var/www/html/glpi/plugins/dashboard/front/main.php(704): DBmysql->fetch_assoc()\n#1 {main}\n  thrown in /var/www/html/glpi/inc/dbmysql.class.php on line 330, referer: http://192.168.0.222/glpi/plugins/dashboard/front/main.php

[Fri Jun 05 11:38:23.183124 2020] [php7:error] [pid 6858] [client 192.168.0.135:56311] PHP Fatal error:  Uncaught Error: Call to a member function fetch_assoc() on bool in /var/www/html/glpi/inc/dbmysql.class.php:330\nStack trace:\n#0 /var/www/html/glpi/plugins/dashboard/front/main.php(704): DBmysql->fetch_assoc()\n#1 {main}\n  thrown in /var/www/html/glpi/inc/dbmysql.class.php on line 330, referer: http://192.168.0.222/glpi/plugins/dashboard/front/main.php
root@newglpi:~#

Obrigado.

**Comment by stdonato** [comment]
Olá. Já fo icorrigido, apenas não lancei a nova release ainda. Baixe o arquivo zip pelo botão Clone or download e teste. Lembre de renomear a pasta para dashboard.

**Comment by allcomnet** [comment]
Ok, funcionou.

![image](https://user-images.githubusercontent.com/66477858/83912342-1929b580-a744-11ea-8b26-fac0b4bc95f8.png)

Muito obrigado.
