### ISSUE TITLE
ERROR  PLUGIN  ON GLPI 9.5

### ISSUE THREAD

**Issue by edgarfabiancalderon** [stdonato/glpi-dashboard#64]
![image](https://user-images.githubusercontent.com/64982932/87838325-4ea1e280-c85c-11ea-9c68-3e8887c2218f.png)

Help install Plugin dashboard on GLPI 9.5 

:(

**Comment by stdonato** [comment]
In image there an error of plugin mreporting. Disable the plugin and test. Maybe incompatible with dashboard.

**Comment by edgarfabiancalderon** [comment]
![image](https://user-images.githubusercontent.com/64982932/88060056-4e8b3680-cb2b-11ea-935b-1340e39a24ee.png)
Disiable the plugin Mreporting 
but the error continues

**Comment by edgarfabiancalderon** [comment]
oh sorry that mistake was mine.



I close case thanks
