### ISSUE TITLE
Dashboard vazio GLPI 9.4.5

### ISSUE THREAD

**Issue by vitorbarreira** [stdonato/glpi-dashboard#65]
Boa tarde.
O dashboard estava funcionando normalmente, mas de um dia para o outro ele não mostra mais gráfico nenhum.

GLPI 9.4.5
dashboard 0.9.6
Ubuntu 18.04.4 LTS
MariaDB 10.1.44
PHP 7.2.24

![glpi_dashboard_error](https://user-images.githubusercontent.com/68598113/88059300-0b38c400-cb3b-11ea-9edb-b4e23864c26e.png)

**Comment by stdonato** [comment]
Por favor baixe a versão mais recente, que já teve esse bug corrigido.

**Comment by vitorbarreira** [comment]
Perdão, mas o problema persiste com as versões 0.9.9 e 0.9.8.

**Comment by stdonato** [comment]
Vitor, verifique as permissões e proprietário da pasta do plugin.
