### ISSUE TITLE
tickets/chamados.php   -   Tickets from all entities!

### ISSUE THREAD

**Issue by pablitobin** [stdonato/glpi-dashboard#66]
We have multiple entities.. If a user has permission just in X entity, when open menu: Tickets - Overall, they can see ALL tickets and not just his entity tickets.
![image](https://user-images.githubusercontent.com/40396227/88330173-a32bde80-ccf0-11ea-894d-0facf4661dda.png)

If the user just clicks in By Entity and filter by entity, he only can choose the entity that he has permission to.

**Comment by stdonato** [comment]
Hi, thank's for your feedback. I'll try and fix.

**Comment by stdonato** [comment]
What yours glpi version? In config page, which entities are available and add to the user?  There any recursive entity ?
If no entity are selected in config page, the overall page will get all user available entities. 
If an entity is recursive, will get all child entities too.

**Comment by pablitobin** [comment]
a user has technician profile for entity X and self service profile for
root (recursive).

glpi 9.4.5

but each user has to just choose the entity? for that purpose they have the
report by entity, right?

**Comment by stdonato** [comment]
When user not choose a entity, the plugin get all active entities from user profile. If one is recursive, all child entities will get too.
I'm trying this: get only active entity, the same that is choosen when access glpi. If want a different entity, just change in glpi right upper corner. Config page only necessary if want select multiple entities.

**Comment by pablitobin** [comment]
But they only have permission to see their OWN tickets in the recursive
entities. I mean, Root Entity (R) scope, they only can see their OWN
tickets, they can see tickets that are not created by them.

**Comment by stdonato** [comment]
The dashboard is an administrative tool. No for individual technician. Is for supervisors and admins follow tickets status across entities and groups. There's no option to view tickets by personal profile, is all based in entities. Technicians and requesters can use your profile direct in GLPI.
