### ISSUE TITLE
Error DBmysql::fetchAssoc() glpi v9.5 dashboard v(0.9.9, 0.9.8, 0.9.7)

### ISSUE THREAD

**Issue by jefrsonquintero** [stdonato/glpi-dashboard#71]
![Error-glpidashboard](https://user-images.githubusercontent.com/34893365/100451602-b1ff1500-3085-11eb-8442-6c97294c46ca.JPG)

Buen día estimado,

Tengo el siguiente error y quisiera saber si es un problema del proyecto o un de mi versión de php 7.2.12. Gracias

**Comment by stdonato** [comment]
Try the new release. 1.0.1

**Comment by jefrsonquintero** [comment]
It works thank you
